/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file outputs.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Functions to place text on the display module.
 *
 ******************************************************************************/

/*
 * RangeFinder GroupLab (c) 2023-24 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef OUTPUTS_H
#define OUTPUTS_H

#ifdef __cplusplus
extern "C" {
#endif

void initialize_board(void);
void display_string(int row, char const string[]);
void refresh_display(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //OUTPUTS_H
