/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file RangeFinder.cpp
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for RangeFinder GroupLab.
 *
 ******************************************************************************/

/*
 * RangeFinder GroupLab (c) 2023-24 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#include <CowPi.h>
#include "alarm.h"
#include "outputs.h"
#include "sensor.h"
#include "shared_variables.h"
#include "user_controls.h"

FILE *display;


void setup() {
    initialize_board();
    pinMode(TRIGGER, OUTPUT);
    pinMode(ECHO, INPUT_PULLUP);
    pinMode(BUZZER, OUTPUT);
    initialize_controls();
    initialize_sensor();
    initialize_alarm();
}

void loop() {
    static char buffer[17];
    cowpi_timer_t volatile *timer = (cowpi_timer_t *) (0x40054000);
    uint32_t time = timer->raw_lower_word;
    sprintf(buffer, "%9lu.%06lu", time / 1000000, time % 1000000);
    display_string(7, buffer);
    refresh_display();
    manage_controls();
    manage_sensor();
    manage_alarm();
}
