/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file user_controls.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Code to get inputs from the user.
 *
 ******************************************************************************/

/*
 * RangeFinder GroupLab (c) 2023 Christopher A. Bohn
 *
 * Assignment and starter code licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef USER_CONTROLS_H
#define USER_CONTROLS_H

#ifdef __cplusplus
extern "C" {
#endif

void initialize_controls(void);
void manage_controls(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif //USER_CONTROLS_H
